matrix:
  include:
  - language: node_js
    cache:
      directories:
        - client/node_modules
    node_js:
      - 10
    os:
      - linux
    before_install: cd client
    install: npm install
    script:
      - npm run ci:build
      # - npm run test
    before_deploy: npm install -g now --no-save
    deploy:
      - provider: script
        script: now --token $NOW_TOKEN --public build
        skip_cleanup: true
        on:
          all_branches: true
          master: false
      - provider: script
        script: cp now.json build && cd build && now --token $NOW_TOKEN --public && now alias --token $NOW_TOKEN staging.rtop.khoanguyen.me
        skip_cleanup: true
        on:
          master: true
