version: "3.6"
services:
  postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD:mysecretpassword"
    restart: always
  migration:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile-migration
    environment:
      - HASURA_ENDPOINT=http://graphql-engine:8080
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/postgres
    command: ["sh", "./wait-for-pg.sh", "postgres", "npm run migrate"]

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha12
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/postgres
      - HASURA_GRAPHQL_ACCESS_KEY=${HASURA_ACCESS_KEY}
      - HASURA_GRAPHQL_AUTH_HOOK=http://auth/auth/webhook
    command: >
      /bin/sh -c "graphql-engine serve --enable-console;"
  auth:
    build:
      context: auth
      args:
        - NODE_ENV=production
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
      - JWT_TOKEN=${JWT_TOKEN}
      - HASURA_ENDPOINT=http://graphql-engine:8080/v1alpha1/graphql
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - FRONTEND_AUTH_CALLBACK=${FRONTEND_URL}/auth/callback
      - FRONTEND_AUTH_FAILURE=${FRONTEND_URL}/auth/failure
    depends_on:
      - graphql-engine
